// Stable, machine-readable error codes shared across the codec, protocol, and HTTP layers.
//
// Every thrown error carries a `.code` from CODES below. The HTTP layer maps codes to
// bounded JSON error responses with appropriate status; it NEVER leaks stack traces or
// reflects complete untrusted payloads.

export const CODES = Object.freeze({
  // dictionary
  DICT_SCHEMA_INVALID: "DICT_SCHEMA_INVALID",
  DICT_ENTRY_COUNT: "DICT_ENTRY_COUNT",
  DICT_ENTRY_TYPE: "DICT_ENTRY_TYPE",
  DICT_ENTRY_TOO_LONG: "DICT_ENTRY_TOO_LONG",
  DICT_ENTRY_INVALID_UNICODE: "DICT_ENTRY_INVALID_UNICODE",
  DICT_DUPLICATE_ENTRY: "DICT_DUPLICATE_ENTRY",
  DICT_ID_MISMATCH: "DICT_ID_MISMATCH",

  // codec
  CODEC_INVALID_UTF8: "CODEC_INVALID_UTF8",
  CODEC_LONE_SURROGATE: "CODEC_LONE_SURROGATE",
  CODEC_UNKNOWN_TOKEN: "CODEC_UNKNOWN_TOKEN",
  CODEC_TOKENS_NOT_ARRAY: "CODEC_TOKENS_NOT_ARRAY",
  CODEC_TOKEN_NOT_STRING: "CODEC_TOKEN_NOT_STRING",
  CODEC_TOO_MANY_TOKENS: "CODEC_TOO_MANY_TOKENS",
  CODEC_RECONSTRUCTED_TOO_LARGE: "CODEC_RECONSTRUCTED_TOO_LARGE",
  CODEC_BYTE_OUT_OF_RANGE: "CODEC_BYTE_OUT_OF_RANGE",

  // payload packing
  PAYLOAD_BASE64_INVALID: "PAYLOAD_BASE64_INVALID",
  PAYLOAD_BASE64_TOO_LONG: "PAYLOAD_BASE64_TOO_LONG",
  PAYLOAD_COMPRESSED_TOO_LARGE: "PAYLOAD_COMPRESSED_TOO_LARGE",
  PAYLOAD_DECOMPRESSED_TOO_LARGE: "PAYLOAD_DECOMPRESSED_TOO_LARGE",
  PAYLOAD_GZIP_INVALID: "PAYLOAD_GZIP_INVALID",
  PAYLOAD_JSON_INVALID: "PAYLOAD_JSON_INVALID",

  // package (embedded standalone-client bundle)
  PACKAGE_COMPRESSED_TOO_LARGE: "PACKAGE_COMPRESSED_TOO_LARGE",
  PACKAGE_DECOMPRESSED_TOO_LARGE: "PACKAGE_DECOMPRESSED_TOO_LARGE",
  PACKAGE_SCHEMA_INVALID: "PACKAGE_SCHEMA_INVALID",

  // protocol / envelope
  PROTO_BODY_INVALID_JSON: "PROTO_BODY_INVALID_JSON",
  PROTO_BODY_TOO_LARGE: "PROTO_BODY_TOO_LARGE",
  PROTO_JSON_TOO_DEEP: "PROTO_JSON_TOO_DEEP",
  PROTO_FIELD_MISSING: "PROTO_FIELD_MISSING",
  PROTO_FIELD_TYPE: "PROTO_FIELD_TYPE",
  PROTO_VERSION_UNSUPPORTED: "PROTO_VERSION_UNSUPPORTED",
  PROTO_KIND_UNSUPPORTED: "PROTO_KIND_UNSUPPORTED",
  PROTO_ENCODING_UNSUPPORTED: "PROTO_ENCODING_UNSUPPORTED",
  PROTO_DICTIONARY_MISMATCH: "PROTO_DICTIONARY_MISMATCH",
  PROTO_MESSAGEID_INVALID: "PROTO_MESSAGEID_INVALID",

  // transport / client
  CLIENT_REDIRECT_REJECTED: "CLIENT_REDIRECT_REJECTED",
  CLIENT_CORRELATION_MISMATCH: "CLIENT_CORRELATION_MISMATCH",
  CLIENT_TIMEOUT: "CLIENT_TIMEOUT",
  CLIENT_TRANSPORT: "CLIENT_TRANSPORT",
  CLIENT_RESPONSE_TOO_LARGE: "CLIENT_RESPONSE_TOO_LARGE",

  // server
  SERVER_TIMEOUT: "SERVER_TIMEOUT",
  SERVER_BUSY: "SERVER_BUSY",
  SERVER_METHOD_NOT_ALLOWED: "SERVER_METHOD_NOT_ALLOWED",
  SERVER_NOT_FOUND: "SERVER_NOT_FOUND",
  SERVER_INTERNAL: "SERVER_INTERNAL",
});

export class ChannelError extends Error {
  constructor(code, message, { httpStatus } = {}) {
    // message carries the code so logs and assert.throws(/CODE/) can see it;
    // `detail` keeps the clean human text for bounded HTTP error bodies.
    super(`${code}: ${message}`);
    this.name = "ChannelError";
    this.code = code;
    this.detail = message;
    // httpStatus is advisory; the HTTP layer has final say.
    this.httpStatus = httpStatus;
  }
}

export function fail(code, message, opts) {
  throw new ChannelError(code, message, opts);
}
